<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RealisticCourseSeeder extends Seeder
{
    public function run(): void
    {
        $instructor = DB::table('users')->where('email', 'instructor@course.local')->first();
        if (!$instructor) {
            $instructor = DB::table('users')->first();
        }

        $progCat = DB::table('categories')->where('slug', 'programming')->first()->id ?? 1;
        $marketingCat = DB::table('categories')->where('slug', 'marketing')->first()->id ?? 1;
        
        $courses = [
            [
                'instructor_id' => $instructor->id,
                'category_id' => $progCat,
                'title' => 'Профессия Data Scientist с нуля до PRO',
                'slug' => 'data-science-pro',
                'description' => 'Научитесь анализировать данные, строить ML-модели и прогнозировать результаты с помощью Python.',
                'content' => 'Этот курс научит вас работать с данными на профессиональном уровне. Вы изучите Python, SQL, Machine Learning (Scikit-Learn, Pandas, NumPy), а также Deep Learning.',
                'price' => 125000.00,
                'discount_price' => 75000.00,
                'level' => 'beginner',
                'language' => 'ru',
                'duration_minutes' => 7200,
                'thumbnail' => 'courses/python.png',
                'preview_video' => null,
                'requirements' => json_encode(['Знание школьной математики', 'ПК с доступом в интернет']),
                'what_you_will_learn' => json_encode(['Программировать на Python', 'Анализировать данные', 'Создавать ML-модели', 'Работать с Big Data']),
                'target_audience' => json_encode(['Новички', 'Аналитики', 'Разработчики']),
                'is_published' => true,
                'is_featured' => true,
                'rating' => 4.9,
                'reviews_count' => 142,
                'students_count' => 2100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'instructor_id' => $instructor->id,
                'category_id' => $progCat,
                'title' => 'Frontend-разработчик на React и Vue',
                'slug' => 'frontend-react-vue',
                'description' => 'Создавайте современные и интерактивные веб-приложения на самых популярных фреймворках.',
                'content' => 'Полный курс по Frontend-разработке. HTML5, CSS3, JavaScript (ES6+), React.js, Redux, Vue 3. От верстки до деплоя полноценного SPA.',
                'price' => 85000.00,
                'discount_price' => 45000.00,
                'level' => 'intermediate',
                'language' => 'ru',
                'duration_minutes' => 6000,
                'thumbnail' => 'courses/react.png',
                'preview_video' => null,
                'requirements' => json_encode(['Базовые знания HTML/CSS', 'Логическое мышление']),
                'what_you_will_learn' => json_encode(['Разработка SPA', 'Работа с React и Vue', 'Стейт-менеджмент', 'API интеграция']),
                'target_audience' => json_encode(['Junior-разработчики', 'Верстальщики']),
                'is_published' => true,
                'is_featured' => true,
                'rating' => 4.8,
                'reviews_count' => 89,
                'students_count' => 1500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'instructor_id' => $instructor->id,
                'category_id' => $progCat,
                'title' => 'DevOps Инженер: CI/CD, Docker и Kubernetes',
                'slug' => 'devops-engineer-master',
                'description' => 'Станьте востребованным DevOps-инженером. Настройте процессы CI/CD, изучите Docker, Kubernetes и Ansible.',
                'content' => 'Глубокое погружение в мир DevOps. Практические навыки администрирования Linux, контейнеризация приложений, оркестрация и инфраструктура как код (IaC).',
                'price' => 140000.00,
                'discount_price' => 99000.00,
                'level' => 'advanced',
                'language' => 'ru',
                'duration_minutes' => 8400,
                'thumbnail' => 'courses/devops.png',
                'preview_video' => null,
                'requirements' => json_encode(['Базовые знания Linux', 'Понимание принципов работы сетей', 'Навыки программирования (Python/Bash)']),
                'what_you_will_learn' => json_encode(['Настройка CI/CD пайплайнов', 'Работа с Docker и Kubernetes', 'Автоматизация конфигурации', 'Мониторинг и логирование']),
                'target_audience' => json_encode(['Системные администраторы', 'Разработчики', 'Начинающие DevOps-инженеры']),
                'is_published' => true,
                'is_featured' => true,
                'rating' => 4.95,
                'reviews_count' => 230,
                'students_count' => 3200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'instructor_id' => $instructor->id,
                'category_id' => $progCat,
                'title' => 'Мобильная разработка на Flutter',
                'slug' => 'flutter-mobile-dev',
                'description' => 'Создавайте кроссплатформенные мобильные приложения для iOS и Android с помощью Flutter и Dart.',
                'content' => 'Научитесь писать код один раз и запускать его на всех мобильных платформах. В курсе рассматриваются основы Dart, виджеты Flutter, работа с API, стейт-менеджмент (BLoC, Provider) и публикация в сторы.',
                'price' => 95000.00,
                'discount_price' => 60000.00,
                'level' => 'intermediate',
                'language' => 'ru',
                'duration_minutes' => 5400,
                'thumbnail' => 'courses/mobile.png',
                'preview_video' => null,
                'requirements' => json_encode(['Знание любого объектно-ориентированного языка программирования']),
                'what_you_will_learn' => json_encode(['Разработка UI на Flutter', 'Язык Dart', 'Работа с сетью', 'Публикация приложений']),
                'target_audience' => json_encode(['Начинающие мобильные разработчики', 'Web-разработчики, желающие перейти в mobile']),
                'is_published' => true,
                'is_featured' => false,
                'rating' => 4.7,
                'reviews_count' => 65,
                'students_count' => 800,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'instructor_id' => $instructor->id,
                'category_id' => $marketingCat,
                'title' => 'Digital Маркетинг и SEO продвижение',
                'slug' => 'digital-marketing-seo',
                'description' => 'Комплексный курс по интернет-маркетингу: от настройки таргетированной рекламы до SEO-оптимизации.',
                'content' => 'Изучите все инструменты современного маркетолога: SEO, SMM, контекстная реклама, email-маркетинг и веб-аналитика. Реальные кейсы и практические задания.',
                'price' => 70000.00,
                'discount_price' => 35000.00,
                'level' => 'beginner',
                'language' => 'ru',
                'duration_minutes' => 4800,
                'thumbnail' => 'courses/marketing.png',
                'preview_video' => null,
                'requirements' => json_encode(['Базовые навыки работы с компьютером']),
                'what_you_will_learn' => json_encode(['Настройка рекламных кампаний', 'SEO-оптимизация сайтов', 'Продвижение в соцсетях', 'Анализ эффективности (Google Analytics)']),
                'target_audience' => json_encode(['Начинающие маркетологи', 'Владельцы малого бизнеса']),
                'is_published' => true,
                'is_featured' => true,
                'rating' => 4.85,
                'reviews_count' => 112,
                'students_count' => 1800,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'instructor_id' => $instructor->id,
                'category_id' => $progCat,
                'title' => 'Fullstack разработчик на Python (Django + React)',
                'slug' => 'fullstack-python-react',
                'description' => 'Освойте профессию fullstack-разработчика, изучив мощную связку Django (backend) и React (frontend).',
                'content' => 'Курс покрывает весь цикл разработки веб-приложений: создание REST API на Django Rest Framework, интеграция с фронтендом на React, настройка базы данных PostgreSQL и деплой на сервер.',
                'price' => 110000.00,
                'discount_price' => 70000.00,
                'level' => 'advanced',
                'language' => 'ru',
                'duration_minutes' => 7800,
                'thumbnail' => 'courses/python.png',
                'preview_video' => null,
                'requirements' => json_encode(['Основы Python', 'Основы JavaScript', 'Понимание работы интернета']),
                'what_you_will_learn' => json_encode(['Создание API на DRF', 'Разработка SPA на React', 'Связывание фронтенда и бэкенда', 'Деплой приложений']),
                'target_audience' => json_encode(['Junior-разработчики', 'Студенты IT-вузов']),
                'is_published' => true,
                'is_featured' => false,
                'rating' => 4.75,
                'reviews_count' => 88,
                'students_count' => 1200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'instructor_id' => $instructor->id,
                'category_id' => $progCat,
                'title' => 'Программирование на JavaScript для начинающих',
                'slug' => 'javascript-for-beginners',
                'description' => 'Самый популярный язык программирования в мире. Начните свой путь в IT с JavaScript.',
                'content' => 'Пошаговый курс по JavaScript. Изучение синтаксиса, типов данных, функций, работы с DOM и асинхронного программирования (Promises, async/await).',
                'price' => 40000.00,
                'discount_price' => 20000.00,
                'level' => 'beginner',
                'language' => 'ru',
                'duration_minutes' => 3000,
                'thumbnail' => 'courses/react.png',
                'preview_video' => null,
                'requirements' => json_encode(['Умение пользоваться компьютером и браузером']),
                'what_you_will_learn' => json_encode(['Синтаксис JS', 'Взаимодействие с веб-страницей', 'Базовые алгоритмы']),
                'target_audience' => json_encode(['Люди без опыта в программировании']),
                'is_published' => true,
                'is_featured' => false,
                'rating' => 4.6,
                'reviews_count' => 150,
                'students_count' => 3500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'instructor_id' => $instructor->id,
                'category_id' => $progCat,
                'title' => 'Архитектура микросервисов с Docker',
                'slug' => 'microservices-docker-arch',
                'description' => 'Научитесь проектировать масштабируемые системы, используя микросервисный подход и Docker.',
                'content' => 'От монолита к микросервисам. Курс для тех, кто хочет научиться разбивать сложные приложения на независимые компоненты, контейнеризировать их и обеспечивать их взаимодействие.',
                'price' => 125000.00,
                'discount_price' => 85000.00,
                'level' => 'advanced',
                'language' => 'ru',
                'duration_minutes' => 6000,
                'thumbnail' => 'courses/devops.png',
                'preview_video' => null,
                'requirements' => json_encode(['Опыт разработки backend-приложений', 'Понимание баз данных']),
                'what_you_will_learn' => json_encode(['Проектирование архитектуры', 'Работа с Docker и Docker Compose', 'Service Mesh и API Gateway', 'Обеспечение отказоустойчивости']),
                'target_audience' => json_encode(['Backend-разработчики', 'Архитекторы ПО']),
                'is_published' => true,
                'is_featured' => true,
                'rating' => 4.9,
                'reviews_count' => 75,
                'students_count' => 900,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'instructor_id' => $instructor->id,
                'category_id' => $progCat,
                'title' => 'Создание iOS приложений на Swift',
                'slug' => 'ios-swift-development',
                'description' => 'Научитесь создавать нативные приложения для iPhone и iPad с нуля.',
                'content' => 'Полное руководство по разработке под iOS. Язык Swift, фреймворки SwiftUI и UIKit, работа с сетью, локальными базами данных и публикация приложения в App Store.',
                'price' => 105000.00,
                'discount_price' => 65000.00,
                'level' => 'beginner',
                'language' => 'ru',
                'duration_minutes' => 6600,
                'thumbnail' => 'courses/mobile.png',
                'preview_video' => null,
                'requirements' => json_encode(['Компьютер на базе macOS (MacBook/iMac)']),
                'what_you_will_learn' => json_encode(['Программирование на Swift', 'Создание интерфейсов (SwiftUI/UIKit)', 'Интеграция с API', 'Загрузка в App Store']),
                'target_audience' => json_encode(['Начинающие разработчики', 'Владельцы Mac']),
                'is_published' => true,
                'is_featured' => false,
                'rating' => 4.8,
                'reviews_count' => 92,
                'students_count' => 1100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'instructor_id' => $instructor->id,
                'category_id' => $marketingCat,
                'title' => 'SMM-специалист: продвижение в социальных сетях',
                'slug' => 'smm-specialist-pro',
                'description' => 'Освойте профессию SMM-менеджера. Научитесь создавать контент, настраивать таргет и привлекать клиентов.',
                'content' => 'Курс по эффективному продвижению бизнеса в VK, Telegram, Instagram. Разработка стратегии, создание визуального и текстового контента, аналитика и работа с блогерами.',
                'price' => 55000.00,
                'discount_price' => 29000.00,
                'level' => 'beginner',
                'language' => 'ru',
                'duration_minutes' => 3600,
                'thumbnail' => 'courses/marketing.png',
                'preview_video' => null,
                'requirements' => json_encode(['Интерес к социальным сетям', 'Наличие смартфона']),
                'what_you_will_learn' => json_encode(['Создание SMM-стратегии', 'Написание текстов', 'Настройка таргетированной рекламы', 'Анализ конкурентов']),
                'target_audience' => json_encode(['Новички в digital', 'Предприниматели', 'Блогеры']),
                'is_published' => true,
                'is_featured' => true,
                'rating' => 4.75,
                'reviews_count' => 134,
                'students_count' => 2500,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        DB::table('courses')->insert($courses);
    }
}
